name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.8.1
  - python=3.9
  - numpy = 1.24
  - protobuf=3.20.3
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip: 
    - mlflow==2.8.1
    - wandb==0.16.0
